# -*- coding: utf-8 -*-
"""PythonAtCollege.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kF45dkknFdrSPf4E8l9B8jH2Shw6_d3V
"""

import random
import cmath
import math
print(
    "\t\t\tWelcome to sunway college Exam section software::\n\t\t------------------------------------------------------------")
name = input("\t\tEnter the name of the student:: ")
sem = input("\t\tEnter your semester:: ")
address = input("\t\tEnter your address:: ")
rollno = input("\t\tEnter your roll number:: ")
m1 = float(input("\t\tEnter the Marks of Applied Programming:: "))
m2 = float(input("\t\tEnter the Marks of Big Data:: "))
print("\n\n\n\n=======================================================")
print("\t\t\tSuway Int. College\n\t\t\tMaitidevi Kathmandu")
print("----------------------------------------------------------")
print("Student Name: ", name, "\t\t\t\t\tSem= ", sem)
print("Address: ", address, "\t\t\t\t\tRollNo= ", rollno)
print("----------------------------------------------------------")
per = (m1+m2)/2
print("Total Marks:: ", m1+m2, "\t\t\tPercentage:: ", per, " %")
if(per >= 90):
    print("A+")
elif(per >= 80):
    print("A")
elif(per >= 70):
    print("B+")
print("----------------------------------------------------------")
print("=============================Report Statement=============================\n")
print("Mr. ", name, " of ", sem, " semester has got ", per,
      "% in the Final Examination. We wish him for the success ahead in his life.")

# Calculate tge Area of a Triangle [A=(s*(s-a)*(s-b)*(s-c))**(1/2)]
a = float(input("Enter a:: "))
b = float(input("Enter b:: "))
c = float(input("Enter c:: "))
s = (a+b+c)/2
area = (s*(s-a)*(s-b)*(s-c))**(1/2)
calc = math.sqrt((s*(s-a)*(s-b)*(s-c)))
print("Area of a triangle is ", area)
print("Area of a triangle is ", calc)

# Solve Quadratic Equation
a = float(input("Enter a:: "))
b = float(input("Enter b:: "))
c = float(input("Enter c:: "))
d = (b**2) - (4*a*c)
x1 = ((-b - cmath.sqrt(d))/(2*a))
x2 = ((-b + cmath.sqrt(d))/(2*a))
print("The value of x1={0} and x2={1}".format(x1, x2))

# Generate random variable
a = int(input("Enter a:: "))
b = int(input("Enter b:: "))
print(random.randint(a, b))
